### PR TITLE
Upgrade api-lib v2 users KVM support

### PR DESCRIPTION
**Pull request by senare**
Hi, 

I would like to be able to create servers using KVM.

It would look to me like I need to upgrade to api/v2 to accomplish this please provide feedback !

### CODE REVIEW

**Comment by norrland** [comment]
Hi @senare, thanks for the help. This has unfortunately dropped down on my todo-list for too long.
I'll check out your PR and merge if it looks good.

**Comment by norrland** [comment]
@senare Unfortunately this breaks server creation in other platforms that doesn't have the same Users support as KVM.
I will see if I can find a way around this.

**Comment by senare** [comment]
I see I must admit I was only focused on the KVM side of things and didn't proper test it ... sry !

I did manage to create KVM servers which is a nice start at least to me.

**Comment by norrland** [comment]
> I see I must admit I was only focused on the KVM side of things and didn't proper test it ... sry !
> 
> I did manage to create KVM servers which is a nice start at least to me.

No worries. Easy to miss :smile: . There are some changes in how the KVM and VMware platforms behaves.

Using your branch I've been able to find some unexpected behavior that I'll try to work around.
And the KVM vs. VMware is one. Since /server/create in VMware requires `rootpassword` it broke when the CreateServerParams was appended with the WithUser() function.

If you have any good ideas on how to only use WithUser when KVM platform is used that would be awesome!

**Comment by vaimo-magnus** [comment]
Not sure if this is still on the table... but could this simply be an if statement.... 

...withDefaults()

if (d.Get("platform") == "KVM") {
	opts = opts.WithUser(
		d.Get("username").(string),
		[]string{d.Get("publickey").(string)},
		d.Get("password").(string),
	)
}

or that the only pass d to withUser(d) and handle this logic instead there.
there is other solutions but that require more changes.

**Comment by norrland** [comment]
> Not sure if this is still on the table... but could this simply be an if statement....
> 
> ```
> func (p CreateServerParams) WithUser(username string, publicKeys []string, password string) CreateServerParams {
> 	if (p.Platform == "KVM") {
> 		p.Users = append(p.Users, User{
> 			username,
> 			publicKeys,
> 			password,
> 		})
> 	}
> 	return p
> }
> ```
> 
> ofc the order they are called needs to be changed.
> 
> .withDefaults().withUser()

Hi Magnus,
It sure is still on the table. Haven't had the time to test it out just yet. Can hopefully get some time later this week to look at it.

**Comment by senare** [comment]
Jag har testad detta för KVM (eller snarare) jag använder detta för att bygga KVM och det verkar inte som om det går sönder ... dock var det ju snarare andra testfall som inte var OK ?

**Comment by vaimo-magnus** [comment]
Ja, tror inte koden gör något nu... dvs den kommer aldrig lägga till något till opts.

opts.WithUser 

vs.

opts = opts.WithUser

Exempel här: https://play.golang.org/p/ISpVXN71jSw

**Comment by senare** [comment]
> Ja, tror inte koden gör något nu... dvs den kommer aldrig lägga till något till opts.
> 
> opts.WithUser
> 
> vs.
> 
> opts = opts.WithUser
> 
> Exempel här: https://play.golang.org/p/ISpVXN71jSw

I aint saying your are wrong but I am using this currently ...

**Comment by senare** [comment]
Oki, nope I am not .. I am running of a internal repo ... will patch 2 sec

**Comment by norrland** [comment]
@senare @vaimo-magnus I think I've managed with a decent enough solution in #20 .
So I'll be closing this one.

**Pull request closed without merging**
